Repository Quartett/StudyUs-BE, pull requests merged in 2023-12, with the labels that each got.

#1 :sparkles: feat: 회원과 관련된 기능 구현
  accounts/adapters.py
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_alter_studyususer_options_alter_studyususer_managers_and_more.py
  accounts/models.py
  accounts/serializers.py
  accounts/views.py
  studyus/settings.py
  studyus/urls.py
Labels: enhancement

#2 ✨ feat: 댓글 기능 구현
  study/admin.py
  study/models.py
  study/serializers.py
  study/views.py
Labels: enhancement

#3 ✨ feat: 실시간 채팅 기능 구현 및 asgi 파일 세팅
  chat/consumers.py
  chat/models.py
  chat/routing.py
  chat/serializers.py
  studyus/asgi.py
Labels: enhancement

#6 :sparkles: feat: 댓글 수정 및 삭제 추가
  accounts/models.py
  study/models.py
  study/serializers.py
  study/urls.py
  study/views.py
  studyus/urls.py
Labels: enhancement

#7 ✨ feat: 변경된 모델에 맞춰 채팅기능 추가, 스터디그룹 생성시 채팅방 생성 로직 구현
  accounts/migrations/0003_alter_studyususer_profile_image.py
  accounts/migrations/0004_alter_studyususer_profile_image.py
  chat/consumers.py
  chat/migrations/0001_initial.py
  chat/migrations/0002_rename_study_chatroom_study_group.py
  chat/models.py
  study/migrations/0001_initial.py
  study/migrations/0002_studymember.py
  study/migrations/0003_rename_thumnail_studygroup_thumbnail.py
  study/migrations/0004_alter_studygroup_category.py
  study/models.py
  study/serializers.py
  study/views.py
  studyus/urls.py
Labels: enhancement

#10 ✨ feat: 그룹 가입, 탈퇴, 권한양도 구현
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_alter_studyususer_options_alter_studyususer_managers_and_more.py
  study/models.py
  study/serializers.py
  study/urls.py
  study/views.py
Labels: enhancement

#14 :sparkles: feat: 암기카드 생성/수정/삭제/조회 기능 추가
  memorycard/__init__.py
  memorycard/admin.py
  memorycard/apps.py
  memorycard/migrations/0001_initial.py
  memorycard/migrations/__init__.py
  memorycard/models.py
  memorycard/serializers.py
  memorycard/tests.py
  memorycard/urls.py
  memorycard/views.py
  study/migrations/0002_alter_studymember_role_and_more.py
  studyus/settings.py
  studyus/urls.py
Labels: enhancement

#16 :sparkles: feat: 암기카드 주제 기능 추가
  memorycard/models.py
  memorycard/permissions.py
  memorycard/serializers.py
  memorycard/urls.py
  memorycard/views.py
  studyus/urls.py
Labels: enhancement

#20 🐛 fix: MemberOnly 퍼미션 수정
  study/permissions.py
  study/urls.py
  study/views.py
Labels: bug

#25 :sparkles: feat: 암기카드 조회시, 북마크만 보기 기능 추가
  memorycard/migrations/0002_alter_memorycard_options_remove_memorycard_user_and_more.py
  memorycard/views.py
  study/migrations/0003_studygroup_level_studygroup_week_days_and_more.py
Labels: enhancement

#27 💄 📝 Default Profile Image 변경 및 Readme 기본 구성 작성
  README.md
  accounts/models.py
  accounts/serializers.py
Labels: enhancement

#28 :construction_worker: chore: 멤버시리얼라이저에 프로필 이미지 필드 추가
  study/serializers.py
Labels: enhancement

#32 :construction_worker: chore: 댓글에 프로필 이미지 필드 추가
  study/serializers.py
Labels: enhancement

#34 📝 docs: Readme 이미지 삽입, 테스트 계정 추가 및 기능 관련 내용 추가
  README.md
Labels: documentation

#35 :bug: fix: 커스텀 유저 permissionmixin 제거
  accounts/models.py
Labels: bug, enhancement

#36 ✨ feat: 사용자가 가입한 스터디그룹의 채팅 리스트 api 추가
  memorycard/migrations/0001_initial.py
  study/migrations/0002_alter_studygroup_thumbnail.py
  study/urls.py
  study/views.py
Labels: enhancement

#39 :sparkles: feat: 리더 탈퇴 시 자동으로 그룹장 권한 양도 및 그룹장만 남아있을 경우 탈퇴 불가
  study/views.py
Labels: enhancement

#43 :white_check_mark: test: 스터디그룹, 댓글에 대한 생성,수정,삭제 테스트 코드 추가
  study/permissions.py
  study/tests.py
  study/views.py
Labels: enhancement

#42 📝 docs: Readme 기능 관련 설명 추가
  README.md
Labels: documentation

#46 :sparkles: feat: 스터디그룹 디폴트 이미지 지정
  study/models.py
Labels: enhancement

#47 ✨ feat: 스터디그룹 디폴트 이미지 지정
  study/models.py
Labels: enhancement

#48 📝 docs: 오류 및 해결방법 설명 추가 및 기타 이미지 삽입
  README.md
Labels: documentation

#49 📝 docs: 실제 UI 이미지 및 시연 gif 삽입
  README.md
Labels: documentation

#50 📝 docs: 소감 작성 및 개선
  README.md
Labels: documentation

#51 📝 docs: 오타 수정
  README.md
Labels: documentation

#52 📝 docs: 문서 개선
  README.md
Labels: documentation
